# Generated by Django 5.2.13 on 2026-05-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='book',
            new_name='books_book_genre_4a7cdf_idx',
            old_name='books_book_genre_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='books_book_author_b941fe_idx',
            old_name='books_book_author_idx',
        ),
        migrations.RenameIndex(
            model_name='book',
            new_name='books_book_year_d303c9_idx',
            old_name='books_book_year_idx',
        ),
    ]
