# Generated by Django 5.2.13 on 2026-05-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerylog',
            name='quality_controllability',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Контрольованість (1-5)'),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='quality_db_binding',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="Прив'язка до бази (1-5)"),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='quality_explainability',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Пояснюваність (1-5)'),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='quality_relevance',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Релевантність (1-5)'),
        ),
    ]
