# Generated by Django 5.2.13 on 2026-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_quality_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquerylog',
            name='search_mode',
            field=models.CharField(blank=True, choices=[('rag', 'RAG (семантичний пошук + GPT)'), ('gpt', 'GPT-only (без бази)'), ('keyword', 'Keyword search (текстовий пошук)')], max_length=10, null=True, verbose_name='Режим пошуку'),
        ),
    ]
